### PR TITLE
Hash table

### PR DESCRIPTION
**Pull request by TrevorThomp**

### CODE REVIEW

**Comment by TrevorThomp** [comment]
- [x] Top-level README “Table of Contents” is updated
 - [x] Feature tasks for this challenge are completed
 - [x] Unit tests written and passing
     - [x] “Happy Path” - Expected outcome
     - [x] Expected failure
 - [x] README for this challenge is complete
     - [x] Summary, Description, Approach & Efficiency, Solution
     - [x] Link to code
     - [x] Picture of whiteboard

**Comment by natkiypie** [comment]
- In README.md links to Travis-CI and PR are wrong

Let us know when these are corrected and we'll give you a grade!

**Comment by TrevorThomp** [comment]
@natkiypie Ok these links should be updated now

**Comment by natkiypie** [comment]
I understand it's a pain in the ass to whiteboard the code when you're going to type it into your text editor anyway. But please do this in the future! My hands are tied.

**Pull request merged**
